[package]
name = "devis-spécial"
version = "0.1.0"
authors = ["Jérémy Belpois <jeremy@lyoko.net>"]
edition = "2018"
publish = false
description = """

"""
license = "MIT"

[dependencies]
rand = "0.7.2"
